FROM node:16.3.0

RUN apt update -y && apt install fswebcam ffmpeg -y

WORKDIR /server

COPY . /server
RUN npm install -g npm
RUN npm install

VOLUME /mms_shared_volume
EXPOSE 3000
CMD [ "npm", "start" ]
