FROM arm32v7/node:16.3.0

RUN apt update -y && apt-get install -y apt-utils && apt install fswebcam -y

WORKDIR /server

COPY . /server
RUN npm install -g npm
RUN npm install

VOLUME /demo_model_mms_helper_shared_volume
EXPOSE 3000
CMD [ "npm", "start" ]
