service: ieam-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  ieam:
    handler: src/ieam.handler
    events:
      - http:
          method: post
          path: /ieam
          cors: true
      - http:
          path: /score/{pathvar+}
          method: get
      - http:
          method: post
          path: /upload
          cors: true
  static:
    handler: src/static.handler
    events:
      - http:
          method: get
          path: /
          cors: true
      - http:
          path: /static/{pathvar+}
          method: get
      - http:
          path: /images/{pathvar+}
          method: get
